# Generated by Django 2.2.9 on 2020-01-21 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SomethingElse",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("char1", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Something",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date1", models.DateField(blank=True, null=True)),
                ("date2", models.DateField(blank=True, null=True)),
                ("bool1", models.BooleanField(default=True)),
                ("bool2", models.NullBooleanField()),
                ("bool3", models.BooleanField(default=False)),
                ("int1", models.IntegerField(blank=True, null=True)),
                ("int2", models.IntegerField(blank=True, null=True)),
                ("int3", models.IntegerField(blank=True, null=True)),
                ("datetime1", models.DateTimeField(auto_now=True, null=True)),
                (
                    "relation1",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="something.SomethingElse"
                    ),
                ),
            ],
        ),
    ]
