# Generated by Django 2.2.9 on 2020-01-21 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("something", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(model_name="somethingelse", old_name="a", new_name="char1",),
    ]
